/**
 * Generate or check Jace Commander's in-process copy of the canonical tool
 * manifest (@agent-control-stack/jc-tool-manifest).
 *
 *   tsx scripts/jc-tool-manifest.ts --check   # CI: fail on any drift
 *   tsx scripts/jc-tool-manifest.ts           # rewrite the generated file
 *
 * Generated (byte-for-byte):
 *   vendor/desktop-commander/src/jace-commander/manifest.generated.ts
 *
 * Jace Commander cannot import the workspace package (vendor/desktop-commander
 * is a subtree built outside the npm workspace graph), so its tools/list,
 * policy table and CLI verb table are all derived from this one generated
 * file instead of hand-maintained arrays.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { jcPortableManifest } from "../packages/jc-tool-manifest/src/index.js";

export const JC_GENERATED_MANIFEST_PATH = "vendor/desktop-commander/src/jace-commander/manifest.generated.ts";

export function renderJcGeneratedManifest(): string {
  const manifest = jcPortableManifest();
  return [
    "// GENERATED by scripts/jc-tool-manifest.ts from packages/jc-tool-manifest. Do not edit.",
    "// Regenerate from the repository root: npm run jc-contracts:generate",
    "// CI fails on drift: npm run jc-contracts:check",
    "",
    "export interface JcManifestTool {",
    "  readonly name: string;",
    "  readonly description: string;",
    "  readonly inputSchema: Readonly<Record<string, unknown>>;",
    "  readonly scopes: readonly string[];",
    "  readonly actionKind: string;",
    "  readonly risk: string;",
    "  readonly requiresApproval: boolean;",
    "  readonly group: string;",
    "  readonly pathArguments: readonly string[];",
    "  readonly cliCommands: readonly string[];",
    "}",
    "",
    "export interface JcManifest {",
    "  readonly version: string;",
    "  readonly manifestHash: string;",
    "  readonly scopes: readonly string[];",
    "  readonly tools: readonly JcManifestTool[];",
    "}",
    "",
    `export const JC_MANIFEST: JcManifest = ${JSON.stringify(manifest, null, 2)};`,
    ""
  ].join("\n");
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const target = resolve(repositoryRoot, JC_GENERATED_MANIFEST_PATH);
  const expected = renderJcGeneratedManifest();
  const actual = await readFile(target, "utf8").catch(() => undefined);
  if (actual !== expected) {
    if (process.argv.includes("--check")) {
      console.error(`${JC_GENERATED_MANIFEST_PATH} is out of date with jc-tool-manifest; run npm run jc-contracts:generate`);
      process.exit(1);
    }
    await writeFile(target, expected);
    console.log(`wrote ${JC_GENERATED_MANIFEST_PATH}`);
  } else {
    console.log(`${JC_GENERATED_MANIFEST_PATH} is up to date`);
  }
}
