import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  gatewayMcpInputSchemas,
  MCP_PROTOCOL_VERSION,
  mcpRequiredScopes,
  mcpToolAnnotations,
  mcpToolDescription,
  mcpToolNames,
  PUBLIC_CONTRACT_VERSION,
  publicContractExamples,
  publicHttpOperations,
  remoteMcpToolNames
} from "../apps/gateway/src/public-contracts.js";
import {
  classifyBreakingChanges,
  type CompatibilitySurface
} from "../apps/gateway/src/public-contract-compatibility.js";
import { z } from "zod";

type JsonObject = Record<string, unknown>;

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generatedRoot = resolve(repositoryRoot, "contracts/public/v1");
const checkOnly = process.argv.includes("--check");
const updateBaseline = process.argv.includes("--update-baseline");

const schemas = Object.fromEntries(
  Object.entries(gatewayMcpInputSchemas).map(([name, schema]) => [name, jsonSchema(schema)])
);

const openapi = {
  openapi: "3.1.0",
  info: {
    title: "Agent Control Stack public HTTP API",
    version: PUBLIC_CONTRACT_VERSION,
    description: "Generated from the Zod schemas used by the ACS gateway runtime."
  },
  paths: publicHttpOperations.reduce<Record<string, JsonObject>>((paths, operation) => {
    paths[operation.path] = {
      ...paths[operation.path],
      [operation.method]: {
        operationId: operation.operationId,
        summary: operation.summary,
        ...(pathParameters(operation.path).length > 0
          ? {
              parameters: pathParameters(operation.path).map((name) => ({
                name,
                in: "path",
                required: true,
                schema: { type: "string", minLength: 1 }
              }))
            }
          : {}),
        ...(operation.requestSchema
          ? {
              requestBody: {
                required: true,
                content: {
                  "application/json": {
                    schema: jsonSchema(operation.requestSchema)
                  }
                }
              }
            }
          : {}),
        responses: {
          [String(operation.successStatus ?? 200)]: { description: "Successful response." },
          "400": { description: "Boundary validation failed." },
          "401": { description: "Authentication is required." },
          "403": { description: "The authenticated principal is not authorized." }
        }
      }
    };
    return paths;
  }, {})
};

const mcp = {
  schemaVersion: `acs.gateway-mcp.${PUBLIC_CONTRACT_VERSION}`,
  protocolVersion: MCP_PROTOCOL_VERSION,
  tools: mcpToolNames.map((name) => ({
    name,
    exposure:
      name === "approve_work_item"
        ? "prohibited_over_mcp"
        : remoteMcpToolNames.includes(name)
          ? "remote"
          : "development_only",
    description: mcpToolDescription(name),
    inputSchema: schemas[name],
    requiredScopes: mcpRequiredScopes(name),
    annotations: mcpToolAnnotations(name)
  }))
};

const examples = {
  schemaVersion: `acs.public-contract-examples.${PUBLIC_CONTRACT_VERSION}`,
  examples: publicContractExamples
};

const generatedClient = `// Generated by scripts/public-contracts.ts. Do not edit.
const operations = ${JSON.stringify(
  Object.fromEntries(
    publicHttpOperations.map((operation) => [
      operation.operationId,
      { method: operation.method.toUpperCase(), path: operation.path }
    ])
  ),
  null,
  2
)};

export function createPublicApiClient(transport) {
  return Object.fromEntries(Object.entries(operations).map(([operationId, operation]) => [
    operationId,
    ({ path = {}, body, headers = {} } = {}) => transport({
      method: operation.method,
      path: Object.entries(path).reduce(
        (value, [name, replacement]) => value.replace(\`{\${name}}\`, encodeURIComponent(String(replacement))),
        operation.path
      ),
      headers,
      ...(body === undefined ? {} : { body })
    })
  ]));
}

export function createGatewayMcpClient(transport) {
  return {
    callTool(name, arguments_, options = {}) {
      return transport({
        method: "POST",
        path: "/mcp",
        headers: options.headers ?? {},
        body: {
          jsonrpc: "2.0",
          id: options.id ?? 1,
          method: "tools/call",
          params: { name, arguments: arguments_ }
        }
      });
    }
  };
}
`;

const manifest = {
  schemaVersion: "acs.public-contract-manifest.v1",
  contractVersion: PUBLIC_CONTRACT_VERSION,
  generatedFiles: ["openapi.json", "mcp-tools.json", "examples.json", "client.mjs"],
  sourceFiles: ["apps/gateway/src/public-contracts.ts", "apps/gateway/src/mcp.ts", "apps/gateway/src/server.ts"],
  hashes: {
    "openapi.json": digest(openapi),
    "mcp-tools.json": digest(mcp),
    "examples.json": digest(examples),
    "client.mjs": digestText(generatedClient)
  }
};

const outputs = new Map<string, unknown>([
  ["openapi.json", openapi],
  ["mcp-tools.json", mcp],
  ["examples.json", examples],
  ["client.mjs", generatedClient],
  ["manifest.json", manifest]
]);

await validateExamples();
await validateCompatibility(openapi, mcp);

if (checkOnly) {
  const drift: string[] = [];
  for (const [filename, value] of outputs) {
    const expected = render(filename, value);
    const path = resolve(generatedRoot, filename);
    const actual = await readOptional(path);
    if (actual !== expected) drift.push(filename);
  }
  if (drift.length > 0) {
    throw new Error(`generated public contracts drifted: ${drift.join(", ")}; run npm run contracts:generate`);
  }
  process.stdout.write(`public contracts are current (${outputs.size} generated files)\n`);
} else {
  await mkdir(generatedRoot, { recursive: true });
  for (const [filename, value] of outputs) {
    await writeFile(resolve(generatedRoot, filename), render(filename, value));
  }
  if (updateBaseline) {
    await writeFile(
      resolve(generatedRoot, "compatibility-baseline.json"),
      serialize(compatibilitySurface(openapi, mcp))
    );
  }
  process.stdout.write(`generated ${outputs.size} public contract files\n`);
}

function jsonSchema(schema: z.ZodType): JsonObject {
  return z.toJSONSchema(schema, {
    target: "draft-2020-12",
    unrepresentable: "any",
    io: "input"
  }) as JsonObject;
}

async function validateExamples(): Promise<void> {
  gatewayMcpInputSchemas.create_work_item.parse(publicContractExamples.createWorkItem);
  gatewayMcpInputSchemas.approve_work_item.parse({
    id: "wrk_example",
    ...publicContractExamples.approveWorkItem
  });
  const envelope = publicContractExamples.listWorkItemsMcp;
  if (envelope.jsonrpc !== "2.0" || envelope.method !== "tools/call" || envelope.params.name !== "list_work_items") {
    throw new Error("generated MCP example is not a tools/call request");
  }
  gatewayMcpInputSchemas.list_work_items.parse(envelope.params.arguments);
}

async function validateCompatibility(nextOpenapi: JsonObject, nextMcp: JsonObject): Promise<void> {
  if (updateBaseline) return;
  const baselinePath = resolve(generatedRoot, "compatibility-baseline.json");
  const baselineText = await readOptional(baselinePath);
  if (!baselineText) {
    throw new Error("compatibility baseline is missing; initialize it with --update-baseline");
  }
  const baseline = JSON.parse(baselineText) as CompatibilitySurface;
  const next = compatibilitySurface(nextOpenapi, nextMcp);
  const breaks = classifyBreakingChanges(baseline, next);
  if (breaks.length === 0) return;

  const declarationsPath = resolve(repositoryRoot, "contracts/public/breaking-changes.json");
  const declarations = JSON.parse(await readFile(declarationsPath, "utf8")) as {
    changes?: Array<{ id?: string; contractVersion?: string }>;
  };
  const documented = new Set(
    (declarations.changes ?? [])
      .filter((change) => change.contractVersion === PUBLIC_CONTRACT_VERSION)
      .map((change) => change.id)
  );
  const undocumented = breaks.filter((change) => !documented.has(change));
  if (undocumented.length > 0) {
    throw new Error(`undocumented breaking public contract changes: ${undocumented.join(", ")}`);
  }
}

function compatibilitySurface(openapiDocument: JsonObject, mcpDocument: JsonObject): CompatibilitySurface {
  const paths = openapiDocument.paths as Record<string, Record<string, JsonObject>>;
  const operations: CompatibilitySurface["operations"] = {};
  for (const [path, methods] of Object.entries(paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      const schema = (
        ((operation.requestBody as JsonObject | undefined)?.content as JsonObject | undefined)?.["application/json"] as
          JsonObject | undefined
      )?.schema as JsonObject | undefined;
      operations[`${method.toUpperCase()} ${path}`] = schemaShape(schema);
    }
  }
  const tools: CompatibilitySurface["tools"] = {};
  for (const tool of mcpDocument.tools as Array<JsonObject>) {
    tools[String(tool.name)] = schemaShape(tool.inputSchema as JsonObject);
  }
  return { operations, tools };
}

function schemaShape(schema: JsonObject | undefined): CompatibilitySurface["operations"][string] {
  const properties = (schema?.properties as JsonObject | undefined) ?? {};
  return {
    required: sortedStrings(schema?.required),
    properties: Object.keys(properties).sort(),
    propertyTypes: Object.fromEntries(
      Object.entries(properties).map(([name, property]) => [
        name,
        JSON.stringify((property as JsonObject).type ?? null)
      ])
    ),
    propertyEnums: Object.fromEntries(
      Object.entries(properties)
        .map(([name, property]) => [name, sortedStrings((property as JsonObject).enum)] as const)
        .filter(([, values]) => values.length > 0)
    )
  };
}

function sortedStrings(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").sort() : [];
}

function pathParameters(path: string): string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1] ?? "").filter(Boolean);
}

function serialize(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function digest(value: unknown): string {
  return `sha256:${createHash("sha256").update(serialize(value)).digest("hex")}`;
}

function digestText(value: string): string {
  return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

function render(filename: string, value: unknown): string {
  return filename.endsWith(".mjs") ? String(value) : serialize(value);
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}
