/**
 * ACPX-backed MCP tools: acpx_list_sessions, acpx_get_session, acpx_exec,
 * acpx_prompt, acpx_cancel.
 *
 * Security model (see project security review for the full rationale):
 * - The `acpx` executable is never taken from tool input; it is always the
 *   literal command name "acpx" (or, only for this module's own test suite,
 *   an env-var override that MCP tool arguments can never influence).
 * - The ACP agent is restricted to ACPX_AGENT_ALLOWLIST below — an
 *   application-controlled list, not an arbitrary client-supplied command.
 * - argv is always an explicit array passed to a shell:false spawn
 *   (see acpx-process.ts); prompt text is always exactly one argv element,
 *   placed after a literal `--` so ACPX's own option parser can never
 *   reinterpret it (verified against the installed ACPX's commander.js
 *   behavior — see test-acpx-tools.js).
 * - Raw ACPX flags (--approve-all, --policy, --agent, --allowed-tools, ...)
 *   are never constructed from tool input; only the fixed, safe flag set
 *   built by buildGlobalArgv/the per-tool argv builders below is ever used.
 * - Every cwd goes through validateAcpxCwd (validatePath + existing-directory
 *   check) before it is used for anything.
 * - session_id is an opaque handle generated by this module. It is never
 *   passed to ACPX directly, never treated as a path/agent/argv/PID; it is
 *   only ever used to look up {agent, cwd, acpxSessionId} in the in-memory
 *   registry below. Unknown or stale session_ids fail closed.
 */

import crypto from 'crypto';
import fs from 'fs/promises';
import { validatePath } from './filesystem.js';
import { runTypedProcess, TypedProcessResult } from './acpx-process.js';
import { ServerResult } from '../types.js';

// ---------------------------------------------------------------------------
// Agent allowlist
// ---------------------------------------------------------------------------

/**
 * Application-controlled allowlist of ACPX agent subcommands. Verified
 * against `acpx --version` (0.12.1) and the "Commands" section of
 * `acpx --help` at implementation time — every entry below is a named agent
 * subcommand ACPX itself advertises (as opposed to generic commands like
 * `exec`/`prompt`/`cancel`/`sessions`/`config`/`compare`/`flow`, which are
 * not agent names). Re-verify this list against `acpx --help` before adding
 * an entry; never derive it from client input.
 */
export const ACPX_AGENT_ALLOWLIST: readonly string[] = [
  'pi', 'openclaw', 'codex', 'claude', 'gemini', 'cursor', 'copilot',
  'droid', 'fast-agent', 'grok-build', 'iflow', 'kilocode', 'kimi',
  'kiro', 'mux', 'opencode', 'qoder', 'qwen', 'trae',
];

const ACPX_AGENT_SET = new Set(ACPX_AGENT_ALLOWLIST);

function isAllowedAgent(agent: string): boolean {
  return ACPX_AGENT_SET.has(agent);
}

// ---------------------------------------------------------------------------
// Executable resolution
// ---------------------------------------------------------------------------

/**
 * Test-only override. Never read from, or settable via, MCP tool arguments —
 * this is an environment variable the test process sets on itself before
 * calling these functions directly (see test/test-acpx-tools.js).
 */
const ACPX_BIN_TEST_OVERRIDE_ENV = 'DESKTOP_COMMANDER_ACPX_BIN_FOR_TESTS';

function getAcpxExecutable(): string {
  const override = process.env[ACPX_BIN_TEST_OVERRIDE_ENV];
  return override && override.trim().length > 0 ? override : 'acpx';
}

// ---------------------------------------------------------------------------
// cwd validation
// ---------------------------------------------------------------------------

async function validateAcpxCwd(requestedCwd: string): Promise<string> {
  const resolved = await validatePath(requestedCwd);
  const stat = await fs.stat(resolved).catch(() => null);
  if (!stat || !stat.isDirectory()) {
    throw new Error(`cwd does not exist or is not a directory: ${requestedCwd}`);
  }
  return resolved;
}

function requireAcpxSessionName(record: AcpxSessionRecord): string {
  if (!record.acpxSessionId) {
    throw new Error('registered ACPX session has no stable ACPX session name');
  }
  return record.acpxSessionId;
}

// ---------------------------------------------------------------------------
// Opaque in-memory session registry
// ---------------------------------------------------------------------------

interface AcpxSessionRecord {
  sessionId: string;
  agent: string;
  cwd: string;
  acpxSessionId?: string;
  createdAt: number;
  lastSeenAt: number;
}

const sessionRegistry = new Map<string, AcpxSessionRecord>();

function findExistingRegistration(agent: string, cwd: string, acpxSessionId?: string): AcpxSessionRecord | undefined {
  for (const record of sessionRegistry.values()) {
    if (record.agent === agent && record.cwd === cwd) {
      if (acpxSessionId === undefined || record.acpxSessionId === acpxSessionId) {
        return record;
      }
    }
  }
  return undefined;
}

function registerSession(agent: string, cwd: string, acpxSessionId?: string): AcpxSessionRecord {
  const existing = findExistingRegistration(agent, cwd, acpxSessionId);
  if (existing) {
    existing.lastSeenAt = Date.now();
    if (acpxSessionId && !existing.acpxSessionId) existing.acpxSessionId = acpxSessionId;
    return existing;
  }
  const record: AcpxSessionRecord = {
    sessionId: crypto.randomUUID(),
    agent,
    cwd,
    acpxSessionId,
    createdAt: Date.now(),
    lastSeenAt: Date.now(),
  };
  sessionRegistry.set(record.sessionId, record);
  return record;
}

function lookupSession(sessionId: string): AcpxSessionRecord | undefined {
  return sessionRegistry.get(sessionId);
}

/** Test-only: clear registry state between test cases. */
export function __resetAcpxSessionRegistryForTests(): void {
  sessionRegistry.clear();
}

// ---------------------------------------------------------------------------
// argv / process helpers
// ---------------------------------------------------------------------------

const LOCAL_OP_TIMEOUT_MS = 15_000;
const LOCAL_OP_MAX_OUTPUT_CHARS = 1_000_000;
const MAX_OUTPUT_CHARS_CEILING = 2_000_000;

function buildGlobalArgv(cwd: string, timeoutMs: number): string[] {
  const timeoutSeconds = Math.max(1, Math.ceil(timeoutMs / 1000));
  return ['--format', 'json', '--json-strict', '--timeout', String(timeoutSeconds), '--cwd', cwd];
}

async function runAcpx(argv: string[], cwd: string, timeoutMs: number, maxOutputChars: number): Promise<TypedProcessResult> {
  const cappedChars = Math.min(maxOutputChars, MAX_OUTPUT_CHARS_CEILING);
  return runTypedProcess({
    executable: getAcpxExecutable(),
    argv,
    cwd,
    timeoutMs,
    maxStdoutChars: cappedChars,
    maxStderrChars: cappedChars,
  });
}

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function errorResult(text: string): ServerResult {
  return {
    content: [{ type: 'text', text: `Error: ${text}` }],
    isError: true,
  };
}

function jsonResult(payload: unknown): ServerResult {
  return { content: [{ type: 'text', text: JSON.stringify(payload, null, 2) }] };
}

function agentAllowlistError(agent: string): ServerResult {
  return errorResult(`agent "${agent}" is not in the allowed ACPX agent list: ${ACPX_AGENT_ALLOWLIST.join(', ')}`);
}

// ---------------------------------------------------------------------------
// ACPX stdout parsing
// ---------------------------------------------------------------------------

function tryParseJson(text: string): { ok: true; value: any } | { ok: false } {
  const trimmed = text.trim();
  if (trimmed.length === 0) return { ok: false };
  try {
    return { ok: true, value: JSON.parse(trimmed) };
  } catch {
    return { ok: false };
  }
}

interface ParsedNdjson {
  events: any[];
  allLinesValidJson: boolean;
}

/** exec/prompt emit newline-delimited JSON-RPC frames under --json-strict. */
function parseNdjson(text: string): ParsedNdjson {
  const lines = text.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
  const events: any[] = [];
  let allValid = lines.length > 0;
  for (const line of lines) {
    const parsed = tryParseJson(line);
    if (parsed.ok) {
      events.push(parsed.value);
    } else {
      allValid = false;
    }
  }
  return { events, allLinesValidJson: allValid };
}

function extractAssistantText(events: any[]): string {
  let text = '';
  for (const event of events) {
    const update = event?.params?.update;
    if (update?.sessionUpdate === 'agent_message_chunk' && update.content?.type === 'text') {
      text += update.content.text ?? '';
    }
  }
  return text;
}

function extractNewAcpSessionId(events: any[]): string | undefined {
  for (const event of events) {
    if (event?.method === undefined && typeof event?.result?.sessionId === 'string') {
      return event.result.sessionId;
    }
  }
  return undefined;
}

function extractFinalResult(events: any[]): any {
  for (let i = events.length - 1; i >= 0; i--) {
    const event = events[i];
    if (event && 'result' in event && event.id !== undefined && event.id !== null) {
      return event.result;
    }
  }
  return undefined;
}

function extractRpcError(events: any[]): any {
  for (const event of events) {
    if (event?.error) return event.error;
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// acpx_list_sessions
// ---------------------------------------------------------------------------

export interface AcpxListSessionsArgs {
  cwd: string;
  agent: string;
  max_results: number;
}

export async function acpxListSessions(args: AcpxListSessionsArgs): Promise<ServerResult> {
  if (!isAllowedAgent(args.agent)) return agentAllowlistError(args.agent);

  let cwd: string;
  try {
    cwd = await validateAcpxCwd(args.cwd);
  } catch (error) {
    return errorResult(`Invalid cwd: ${message(error)}`);
  }

  const argv = [
    ...buildGlobalArgv(cwd, LOCAL_OP_TIMEOUT_MS),
    args.agent, 'sessions', 'list', '--local', '--filter-cwd', cwd,
  ];

  let proc: TypedProcessResult;
  try {
    proc = await runAcpx(argv, cwd, LOCAL_OP_TIMEOUT_MS, LOCAL_OP_MAX_OUTPUT_CHARS);
  } catch (error) {
    return errorResult(`Failed to run acpx: ${message(error)}`);
  }

  if (proc.timedOut) return errorResult(`acpx sessions list timed out after ${LOCAL_OP_TIMEOUT_MS}ms`);
  if (proc.exitCode !== 0) {
    return errorResult(`acpx sessions list failed (exit ${proc.exitCode}): ${proc.stderr || proc.stdout}`);
  }

  const parsed = tryParseJson(proc.stdout);
  if (!parsed.ok || !Array.isArray(parsed.value)) {
    return errorResult(`acpx returned malformed session list output: ${proc.stdout.slice(0, 500)}`);
  }

  const sorted = [...parsed.value].sort((a, b) => {
    const aTime = Date.parse(a?.lastUsedAt ?? '') || 0;
    const bTime = Date.parse(b?.lastUsedAt ?? '') || 0;
    return bTime - aTime;
  });
  const records = sorted.slice(0, args.max_results);

  const sessions = records.map((record: any) => {
    const acpxSessionId = typeof record?.acpSessionId === 'string' ? record.acpSessionId : undefined;
    const reg = registerSession(args.agent, cwd, acpxSessionId);
    return {
      session_id: reg.sessionId,
      agent: args.agent,
      cwd,
      acpx_session_id: reg.acpxSessionId,
      created_at: record?.createdAt,
      last_used_at: record?.lastUsedAt,
      closed: record?.closed,
    };
  });

  return jsonResult({
    sessions,
    total_local_records: parsed.value.length,
    truncated: parsed.value.length > args.max_results,
  });
}

// ---------------------------------------------------------------------------
// acpx_get_session
// ---------------------------------------------------------------------------

export interface AcpxGetSessionArgs {
  session_id: string;
  include_history: boolean;
  history_limit: number;
}

export async function acpxGetSession(args: AcpxGetSessionArgs): Promise<ServerResult> {
  const record = lookupSession(args.session_id);
  if (!record) return errorResult(`Unknown session_id: ${args.session_id}`);

  let cwd: string;
  try {
    cwd = await validateAcpxCwd(record.cwd);
  } catch (error) {
    return errorResult(`Session cwd is no longer valid: ${message(error)}`);
  }
  if (cwd !== record.cwd) {
    return errorResult(`Session scope mismatch for ${args.session_id}`);
  }

  let acpxSessionId: string;
  try {
    acpxSessionId = requireAcpxSessionName(record);
  } catch (error) {
    return errorResult(`Session cannot be resolved safely: ${message(error)}`);
  }

  const showArgv = [...buildGlobalArgv(cwd, LOCAL_OP_TIMEOUT_MS), record.agent, 'sessions', 'show', acpxSessionId];

  let showProc: TypedProcessResult;
  try {
    showProc = await runAcpx(showArgv, cwd, LOCAL_OP_TIMEOUT_MS, LOCAL_OP_MAX_OUTPUT_CHARS);
  } catch (error) {
    return errorResult(`Failed to run acpx: ${message(error)}`);
  }

  const result: Record<string, unknown> = {
    session_id: record.sessionId,
    agent: record.agent,
    cwd: record.cwd,
  };

  if (showProc.timedOut) {
    result.session = null;
    result.session_error = `acpx sessions show timed out after ${LOCAL_OP_TIMEOUT_MS}ms`;
  } else if (showProc.exitCode === 0) {
    const parsed = tryParseJson(showProc.stdout);
    result.session = parsed.ok ? parsed.value : showProc.stdout;
    result.session_parsed = parsed.ok;
  } else {
    result.session = null;
    result.session_error = showProc.stderr || showProc.stdout;
  }

  if (args.include_history) {
    const historyArgv = [
      ...buildGlobalArgv(cwd, LOCAL_OP_TIMEOUT_MS),
      record.agent, 'sessions', 'history', '--limit', String(args.history_limit), acpxSessionId,
    ];

    let historyProc: TypedProcessResult;
    try {
      historyProc = await runAcpx(historyArgv, cwd, LOCAL_OP_TIMEOUT_MS, LOCAL_OP_MAX_OUTPUT_CHARS);
    } catch (error) {
      result.history = null;
      result.history_error = `Failed to run acpx: ${message(error)}`;
      return jsonResult(result);
    }

    if (historyProc.timedOut) {
      result.history = null;
      result.history_error = `acpx sessions history timed out after ${LOCAL_OP_TIMEOUT_MS}ms`;
    } else if (historyProc.exitCode === 0) {
      const parsedHistory = tryParseJson(historyProc.stdout);
      result.history = parsedHistory.ok ? parsedHistory.value : historyProc.stdout;
      result.history_parsed = parsedHistory.ok;
      result.history_truncated = historyProc.stdoutTruncated;
    } else {
      result.history = null;
      result.history_error = historyProc.stderr || historyProc.stdout;
    }
  }

  return jsonResult(result);
}

// ---------------------------------------------------------------------------
// acpx_exec
// ---------------------------------------------------------------------------

export interface AcpxExecArgs {
  cwd: string;
  agent: string;
  prompt: string;
  timeout_ms: number;
  max_output_chars: number;
}

export async function acpxExec(args: AcpxExecArgs): Promise<ServerResult> {
  if (!isAllowedAgent(args.agent)) return agentAllowlistError(args.agent);

  let cwd: string;
  try {
    cwd = await validateAcpxCwd(args.cwd);
  } catch (error) {
    return errorResult(`Invalid cwd: ${message(error)}`);
  }

  const argv = [
    ...buildGlobalArgv(cwd, args.timeout_ms),
    args.agent, 'exec', '--', args.prompt,
  ];

  let proc: TypedProcessResult;
  try {
    proc = await runAcpx(argv, cwd, args.timeout_ms, args.max_output_chars);
  } catch (error) {
    return errorResult(`Failed to run acpx: ${message(error)}`);
  }

  const ndjson = parseNdjson(proc.stdout);
  const assistantText = extractAssistantText(ndjson.events);
  const finalResult = extractFinalResult(ndjson.events);
  const rpcError = extractRpcError(ndjson.events);
  const newAcpSessionId = extractNewAcpSessionId(ndjson.events);

  // Only register a session when ACPX's own verified output supplies a
  // session identity (never speculatively, and never from client input).
  let registeredSessionId: string | undefined;
  if (newAcpSessionId) {
    registeredSessionId = registerSession(args.agent, cwd, newAcpSessionId).sessionId;
  }

  return jsonResult({
    agent: args.agent,
    cwd,
    exit_code: proc.exitCode,
    signal: proc.signal,
    timed_out: proc.timedOut,
    stdout_truncated: proc.stdoutTruncated,
    stderr_truncated: proc.stderrTruncated,
    stdout_is_json: ndjson.allLinesValidJson,
    assistant_text: assistantText.length > 0 ? assistantText : undefined,
    result: finalResult,
    error: rpcError,
    session_id: registeredSessionId,
    stdout: proc.stdout,
    stderr: proc.stderr,
  });
}

// ---------------------------------------------------------------------------
// acpx_prompt
// ---------------------------------------------------------------------------

export interface AcpxPromptArgs {
  session_id: string;
  prompt: string;
  wait: boolean;
  timeout_ms: number;
  max_output_chars: number;
}

export async function acpxPrompt(args: AcpxPromptArgs): Promise<ServerResult> {
  const record = lookupSession(args.session_id);
  if (!record) return errorResult(`Unknown session_id: ${args.session_id}`);

  let cwd: string;
  try {
    cwd = await validateAcpxCwd(record.cwd);
  } catch (error) {
    return errorResult(`Session cwd is no longer valid: ${message(error)}`);
  }
  if (cwd !== record.cwd) {
    return errorResult(`Session scope mismatch for ${args.session_id}`);
  }

  let acpxSessionId: string;
  try {
    acpxSessionId = requireAcpxSessionName(record);
  } catch (error) {
    return errorResult(`Session cannot be resolved safely: ${message(error)}`);
  }

  const argv = [
    ...buildGlobalArgv(cwd, args.timeout_ms),
    record.agent, 'prompt',
    '--session', acpxSessionId,
    ...(args.wait === false ? ['--no-wait'] : []),
    '--', args.prompt,
  ];

  let proc: TypedProcessResult;
  try {
    proc = await runAcpx(argv, cwd, args.timeout_ms, args.max_output_chars);
  } catch (error) {
    return errorResult(`Failed to run acpx: ${message(error)}`);
  }

  const ndjson = parseNdjson(proc.stdout);
  const assistantText = extractAssistantText(ndjson.events);
  const finalResult = extractFinalResult(ndjson.events);
  const rpcError = extractRpcError(ndjson.events);

  record.lastSeenAt = Date.now();

  return jsonResult({
    session_id: record.sessionId,
    agent: record.agent,
    cwd: record.cwd,
    exit_code: proc.exitCode,
    signal: proc.signal,
    timed_out: proc.timedOut,
    stdout_truncated: proc.stdoutTruncated,
    stderr_truncated: proc.stderrTruncated,
    stdout_is_json: ndjson.allLinesValidJson,
    assistant_text: assistantText.length > 0 ? assistantText : undefined,
    result: finalResult,
    error: rpcError,
    stdout: proc.stdout,
    stderr: proc.stderr,
  });
}

// ---------------------------------------------------------------------------
// acpx_cancel
// ---------------------------------------------------------------------------

export interface AcpxCancelArgs {
  session_id: string;
}

export async function acpxCancel(args: AcpxCancelArgs): Promise<ServerResult> {
  const record = lookupSession(args.session_id);
  if (!record) return errorResult(`Unknown session_id: ${args.session_id}`);

  let cwd: string;
  try {
    cwd = await validateAcpxCwd(record.cwd);
  } catch (error) {
    return errorResult(`Session cwd is no longer valid: ${message(error)}`);
  }
  if (cwd !== record.cwd) {
    return errorResult(`Session scope mismatch for ${args.session_id}`);
  }

  let acpxSessionId: string;
  try {
    acpxSessionId = requireAcpxSessionName(record);
  } catch (error) {
    return errorResult(`Session cannot be resolved safely: ${message(error)}`);
  }

  const argv = [...buildGlobalArgv(cwd, LOCAL_OP_TIMEOUT_MS), record.agent, 'cancel', '--session', acpxSessionId];

  let proc: TypedProcessResult;
  try {
    proc = await runAcpx(argv, cwd, LOCAL_OP_TIMEOUT_MS, LOCAL_OP_MAX_OUTPUT_CHARS);
  } catch (error) {
    return jsonResult({ session_id: record.sessionId, status: 'failed', reason: `Failed to run acpx: ${message(error)}` });
  }

  if (proc.timedOut) {
    return jsonResult({ session_id: record.sessionId, status: 'failed', reason: 'cancel command timed out' });
  }
  if (proc.exitCode !== 0) {
    return jsonResult({
      session_id: record.sessionId,
      status: 'failed',
      exit_code: proc.exitCode,
      stderr: proc.stderr,
      stdout: proc.stdout,
    });
  }

  const parsed = tryParseJson(proc.stdout);
  let status: 'accepted' | 'no_active_prompt' | 'failed' = 'failed';
  if (parsed.ok && typeof parsed.value?.cancelled === 'boolean') {
    status = parsed.value.cancelled ? 'accepted' : 'no_active_prompt';
  }

  return jsonResult({
    session_id: record.sessionId,
    status,
    raw: parsed.ok ? parsed.value : proc.stdout,
  });
}
